name: Sync Bitbucket

on:
  schedule:
    - cron: "0 0 * * *"

  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: push
        uses: journeylab-tech/mirror-to-bitbucket-github-action@v2.1.0
        with:
          username: allanoricil-journeylab
          spacename: ascendmarketing
          repository: flowfuse
          password: ${{ secrets.BITBUCKET_APP_PASSWORD_GITHUB }}